version: "3.1"
services:
  graphql-server:
    build:
      context: .
      dockerfile: server/docker/node/Dockerfile
    environment:
      - API_KEY_YOUTUBE
    volumes:
    - ./server:/usr/src/app
    ports:
    - "4000:4000"
    entrypoint: ["sh", "-c"]
    command: ["yarn install && yarn run start"]
  graphql-client:
    build:
      context: .
      dockerfile: client/docker/node/Dockerfile
    volumes:
    - ./client:/usr/src/app
    ports:
    - "8080:8080"
    entrypoint: ["sh", "-c"]
    command: ["yarn install && yarn serve"]
